defect_classes:
- 划痕
- 污点
- 缺失
- 变形
- 异物
paths:
  auto_annotation: true
  default_annotation_dir: E:/PIC_SLM/TEST/OUTPUT/annotations
  default_output_dir: E:/PIC_SLM/TEST/OUTPUT
  default_processed_dir: E:/PIC_SLM/TEST/OUTPUT/dataset/train
  default_source_dir: E:/PIC_SLM/TEST/SOURCE
preprocessing:
  default_augmentation: 基础
  default_format: jpg
  default_size: 224x224
  default_train_ratio: 0.8
training:
  default_batch_size: 32
  default_epochs: 20
  default_learning_rate: 0.001
  default_model: ResNet50
